"""Create threat_events table

Revision ID: efe07c3a3d79
Revises: 
Create Date: 2025-08-27 12:33:37.369521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'efe07c3a3d79'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('threat_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('threat_type', sa.String(length=255), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('seen_before', sa.Boolean(), nullable=True),
    sa.Column('country', sa.String(length=5), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('mitre_technique', sa.String(length=100), nullable=True),
    sa.Column('mitre_id', sa.String(length=20), nullable=True),
    sa.Column('raw_data', sa.Text(), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source_type', sa.String(length=50), nullable=True),
    sa.Column('blocked', sa.Boolean(), nullable=True),
    sa.Column('notified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_threat_events_created_at', 'threat_events', ['created_at'], unique=False)
    op.create_index('idx_threat_events_ip_severity', 'threat_events', ['ip_address', 'severity'], unique=False)
    op.create_index('idx_threat_events_score', 'threat_events', ['score'], unique=False)
    op.create_index(op.f('ix_threat_events_id'), 'threat_events', ['id'], unique=False)
    op.create_index(op.f('ix_threat_events_ip_address'), 'threat_events', ['ip_address'], unique=False)
    op.create_index(op.f('ix_threat_events_severity'), 'threat_events', ['severity'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_threat_events_severity'), table_name='threat_events')
    op.drop_index(op.f('ix_threat_events_ip_address'), table_name='threat_events')
    op.drop_index(op.f('ix_threat_events_id'), table_name='threat_events')
    op.drop_index('idx_threat_events_score', table_name='threat_events')
    op.drop_index('idx_threat_events_ip_severity', table_name='threat_events')
    op.drop_index('idx_threat_events_created_at', table_name='threat_events')
    op.drop_table('threat_events')
    # ### end Alembic commands ###
